# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-22 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0003_mosque_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mosque_main',
        ),
    ]
