# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fr', '0004_delete_mosque_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='mosque_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=1000)),
                ('borough', models.CharField(max_length=1000)),
                ('area', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('postcode', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
            ],
        ),
    ]
