# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0005_mosque_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('mosque_id', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=10000)),
                ('comment_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
