# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0008_auto_20190623_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote_Track',
        ),
    ]
